[workspace]
resolver = "3"
members = ["crates/lib/agent-harness-kit-core"]

[workspace.package]
version = "0.1.0"
authors = ["six5536 <10079653+six5536@users.noreply.github.com>"]
edition = "2024"
rust-version = "1.85"
license = "MIT"
repository = "https://github.com/six5536/agent-harness-kit"
homepage = "https://github.com/six5536/agent-harness-kit"

[workspace.dependencies]
agent-harness-kit-core = { version = "0.1.0", path = "crates/lib/agent-harness-kit-core" }
serde = { version = "1", features = ["derive", "std"] }
serde_json = { version = "1.0", features = ["preserve_order"] }
toml_edit = "0.25"
schemars = "1.2"
insta = "1.47"
proptest = "1.11"
